"""Add ecosystem fields

Revision ID: 47f8ba7150fa
Revises: 
Create Date: 2026-09-03 11:52:08.008052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f8ba7150fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scope', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('scope', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'scope')
    op.drop_column('events', 'scope')
    # ### end Alembic commands ###
